import Navigation from "@/components/navigation";
import { useEagerConnect } from "@/hooks/useEagerConnect";
import type { AppProps } from "next/app";
import Head from "next/head";
import "../styles/globals.css";

function MyApp({ Component, pageProps }: AppProps) {
  useEagerConnect();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navigation />

      <Component {...pageProps} />
    </>
  );
}

export default MyApp;
