import useGetTokens from "@/hooks/view/useGetTokens";
import useWeb3Store from "@/hooks/useWeb3Store";
import { injected } from "@/lib/connectors/metamask";
import Head from "next/head";

function Home() {
  const account = useWeb3Store((state) => state.account);

  async function connect() {
    try {
      await injected.activate();
    } catch (error) {
      console.error(error);
    }
  }

  const { data: basketTokens } = useGetTokens();

  return (
    <div className="p-5">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className="mb-8">
        <div>
          {account ? (
            <p>Connected Address: {account}</p>
          ) : (
            <button onClick={connect}>Connect Wallet</button>
          )}
        </div>
      </nav>

      <main>
        <div>
          <h2 className="mb-4 text-lg font-bold">Deposit</h2>

          <form method="POST" className="space-y-4">
            <div>
              <label className="block" htmlFor="token">
                Select a token
              </label>

              <select name="token" id="token">
                <option value="">Select a token</option>
                {basketTokens?.map((tokenAddress) => (
                  <option key={tokenAddress} value={tokenAddress}>
                    {tokenAddress}
                  </option>
                ))}
              </select>
            </div>

            <div>
              <label className="block" htmlFor="amount">
                Enter amount of token
              </label>

              <input
                autoComplete="off"
                autoCorrect="off"
                inputMode="decimal"
                maxLength={79}
                minLength={1}
                pattern="^[0-9]*[.,]?[0-9]*$"
                placeholder="0.0"
                spellCheck="false"
                type="text"
              />
            </div>

            <div>
              <p>Advanced</p>

              <div>
                <label className="block" htmlFor="slippage">
                  Slippage Percent
                </label>

                <input
                  autoComplete="off"
                  autoCorrect="off"
                  inputMode="decimal"
                  maxLength={4}
                  minLength={1}
                  pattern="^[0-9]*[.,]?[0-9]*$"
                  placeholder="0.10"
                  spellCheck="false"
                  type="text"
                />

                <span>%</span>
              </div>
            </div>
          </form>
        </div>
      </main>
    </div>
  );
}

export default Home;
