import { CONTRACT_ADDRESSES, MaxUint256, TOKEN_ADDRESSES } from "@/constants";
import useERC20 from "@/hooks/contracts/useERC20";
import usePoolRouter from "@/hooks/contracts/usePoolRouter";
import useBlockNumber from "@/hooks/useBlockNumber";
import useUserRewards from "@/hooks/view/useUserRewards";
import { useEagerConnect } from "@/hooks/useEagerConnect";
import useWeb3Store from "@/hooks/useWeb3Store";
import useGetPoolTokens from "@/hooks/view/useGetPoolTokens";
import { useTokenAllowanceForPoolRouter } from "@/hooks/view/useTokenAllowance";
import useTokenBalance from "@/hooks/view/useTokenBalance";
import { injected } from "@/lib/connectors/metamask";
import { BigNumber } from "@ethersproject/bignumber";
import type { TransactionResponse } from "@ethersproject/providers";
import { formatUnits, parseUnits } from "@ethersproject/units";
import Head from "next/head";
import { ChangeEvent, FormEvent, useState } from "react";

function Home() {
  useEagerConnect();

  const account = useWeb3Store((state) => state.account);
  const chainId = useWeb3Store((state) => state.chainId);

  async function connect() {
    try {
      await injected.activate();
    } catch (error) {
      console.error(error);
    }
  }

  const { data: poolTokens } = useGetPoolTokens();
  const { data: blockNumber } = useBlockNumber();

  const { data: userRewards } = useUserRewards(account);

  const poolRouter = usePoolRouter();

  async function getMinPoolAmountOut(
    tokenAddress: string,
    amountToDeposit: string,
    slippage: string
  ) {
    const poolAmountOut: BigNumber = await poolRouter.getSovAmountOutSingle(
      tokenAddress,
      parseUnits(amountToDeposit),
      slippage ? slippage : 1
    );

    return poolAmountOut.mul(100 - Number(slippage)).div(100);
  }

  const [tokenAddress, tokenAddressSet] = useState<string>("");
  const tokenAddressOnChange = (event: ChangeEvent<HTMLSelectElement>) =>
    tokenAddressSet(event.currentTarget.value);

  const [depositAmount, depositAmountSet] = useState<string>("");
  const depositAmountOnChange = (event: ChangeEvent<HTMLInputElement>) =>
    depositAmountSet(event.currentTarget.value);

  const { data: tokenBalance } = useTokenBalance(account, tokenAddress);

  const { data: sovTokenBalance, mutate: sovTokenBalanceMutate } =
    useTokenBalance(account, TOKEN_ADDRESSES.SOV[chainId]);

  const { data: tokenAllowance, mutate: tokenAllowanceMutate } =
    useTokenAllowanceForPoolRouter(tokenAddress, account);

  const needsApproval =
    !!tokenAllowance && !!depositAmount
      ? tokenAllowance.lt(parseUnits(depositAmount))
      : undefined;

  const erc20Contract = useERC20(tokenAddress);

  async function onSubmit(event: FormEvent) {
    event.preventDefault();

    const values = event.target as typeof event.target & {
      token: { value: string };
      amount: { value: string };
      slippage: { value: string };
    };

    try {
      const minPoolAmountOut = await getMinPoolAmountOut(
        values.token.value,
        values.amount.value,
        values.slippage.value
      );

      const tx: TransactionResponse = await poolRouter.deposit(
        values.token.value,
        parseUnits(values.amount.value),
        minPoolAmountOut,
        BigNumber.from(10000)
      );

      await tx.wait();

      await sovTokenBalanceMutate();
    } catch (error) {
      console.error(error);
    }
  }

  async function approve() {
    try {
      const tx: TransactionResponse = await erc20Contract.approve(
        CONTRACT_ADDRESSES.PoolRouter[chainId],
        MaxUint256
      );

      await tx.wait();

      await tokenAllowanceMutate();
    } catch (error) {
      console.error(error);
    }
  }

  return (
    <div className="p-5">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className="mb-8">
        <div>
          {account ? (
            <ul>
              <li>
                <p>Connected Address</p>
                <p>{account}</p>
              </li>
              <li>
                <p>Block Number</p>
                <p>{blockNumber}</p>
              </li>
              <li>
                <p>SOV Balance</p>
                <p>{formatUnits(sovTokenBalance ?? 0)}</p>
              </li>
              <li>
                <p>User Rewards</p>
                <p>{formatUnits(userRewards ?? 0)}</p>
              </li>
            </ul>
          ) : (
            <button onClick={connect}>Connect Wallet</button>
          )}
        </div>
      </nav>

      <main>
        <div>
          <h2 className="mb-4 text-lg font-bold">Deposit</h2>

          <form onSubmit={onSubmit} method="POST" className="space-y-4">
            <div>
              <label className="block" htmlFor="token">
                Select a token
              </label>

              <select
                value={tokenAddress}
                onChange={tokenAddressOnChange}
                name="token"
                id="token"
                required
              >
                <option value="">Select a token</option>
                {poolTokens?.map((token) => (
                  <option key={token.address} value={token.address}>
                    {token.name}
                  </option>
                ))}
              </select>
            </div>

            {tokenAddress && tokenBalance && (
              <div>
                <p>
                  <span>Balance:</span> <span>{formatUnits(tokenBalance)}</span>
                </p>
              </div>
            )}

            <div>
              <label className="block" htmlFor="amount">
                Enter amount of token
              </label>

              <input
                autoComplete="off"
                autoCorrect="off"
                inputMode="decimal"
                maxLength={79}
                minLength={1}
                name="amount"
                required
                id="amount"
                value={depositAmount}
                onChange={depositAmountOnChange}
                pattern="^[0-9]*[.,]?[0-9]*$"
                placeholder="0.0"
                spellCheck="false"
                type="text"
              />
            </div>

            <div>
              <p>Advanced</p>

              <div>
                <label className="block" htmlFor="slippage">
                  Slippage Percent
                </label>

                <input
                  autoComplete="off"
                  autoCorrect="off"
                  inputMode="numeric"
                  id="slippage"
                  name="slippage"
                  min={0}
                  max={99}
                  step={1}
                  placeholder="1"
                  spellCheck="false"
                  type="number"
                />

                <span>%</span>
              </div>
            </div>

            {needsApproval && (
              <div>
                <p>Needs Token Approval</p>

                <button onClick={approve} type="button">
                  Approve Sovreign To Spend Your Token
                </button>
              </div>
            )}

            <button type="submit" disabled={needsApproval}>
              Deposit
            </button>
          </form>
        </div>
      </main>
    </div>
  );
}

export default Home;
